id: P004501
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9260
  title: བཀའ་བརྒྱུད་པའི་ལོ་རྒྱུས་ཟིན་ཐོ།
  author: ''
  volumes:
    e85aff3467734731aedc3fcd0d139018:
      image_group_id: I1KG9498
      title: ''
      volume_number: 1
      total_pages: 76
