id: I981023F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:11:38+00:00'
last_modified: '2022-06-08T01:31:48.610947+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9260
  title: བཀའ་བརྒྱུད་པའི་ལོ་རྒྱུས་ཟིན་ཐོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    EF94:
      image_group_id: I1KG9498
      title: ''
      total_pages: 76
      order: 1
      base_file: EF94.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
